apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: cluster
build:
  artifacts:
  - image: gimpyb/buymebeer-container-prod
    context: payme.beer
    docker:
      dockerfile: Dockerfile
  - image: gimpyb/myphp-container
    context: site-fpm
    docker:
      dockerfile: Dockerfile
  - image: gimpyb/mysite-container-prod
    docker:
      dockerfile: Dockerfile
  - image: gimpyb/mystaticsite-container-prod
    context: staticsite
    docker:
      dockerfile: Dockerfile
  - image: gimpyb/passwordexchange-container-prod
    context: password.exchange/docker
    docker:
      dockerfile: Dockerfile
      noCache: true
deploy:
  kubectl:
    manifests:
    - mysite-dev.yml
    - cert-manager-deployment/cert-route53.yml
    - cert-manager-deployment/route53.yaml
    - cert-manager-deployment/selfsigned-dev.yaml
    - password.exchange/kubernetes/deployment.yaml
    - payme.beer/buymebeer-site.yaml
    - staticsite/mystatic-site.yaml
