---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kiam-server
spec:
  selector:
    matchLabels:
      app: kiam
      role: server
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9620"
      labels:
        app: kiam
        role: server
    spec:
      serviceAccountName: kiam-server
      nodeSelector:
        kubernetes.io/role: master
      # kops master nodes requires this tolerations
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
          operator: "Exists"
      volumes:
        - name: ssl-certs
          secret:
            secretName: server-tls
            # for AWS linux or RHEL distros
            # path: /etc/pki/ca-trust/extracted/pem/
            # debian or ubuntu distros
            # path: /etc/ssl/certs
            #path: /usr/share/ca-certificates
        - name: tls
          secret:
            secretName: server-tls
      containers:
        - name: kiam
          image: quay.io/uswitch/kiam:v4.0 # USE A TAGGED RELEASE IN PRODUCTION
          imagePullPolicy: Always
          command:
            - /kiam
          args:
            - server
            - --json-log
            - --level=warn
            - --bind=0.0.0.0:443
            - --cert=/etc/ssl/certs/tls.crt
            - --key=/etc/ssl/certs/tls.key
            - --ca=/etc/ssl/certs/ca.crt
            - --role-base-arn-autodetect
            - --assume-role-arn=arn:aws:iam::842805395457:role/Kiam_server            
            - --sync=1m
            - --prometheus-listen-addr=0.0.0.0:9620
            - --prometheus-sync-interval=5s
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
          livenessProbe:
            exec:
              command:
              - /kiam
              - health
              - --cert=/etc/ssl/certs/tls.crt
              - --key=/etc/ssl/certs/tls.key
              - --ca=/etc/ssl/certs/ca.crt
              - --server-address=localhost:443
              - --gateway-timeout-creation=1s
              - --timeout=5s
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - /kiam
              - health
              - --cert=/etc/ssl/certs/tls.crt
              - --key=/etc/ssl/certs/tls.key
              - --ca=/etc/ssl/certs/ca.crt
              - --server-address=localhost:443
              - --gateway-timeout-creation=1s
              - --timeout=5s
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
