apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-route53
  annotations:
    iam.amazonaws.com/role: ExternalRole


spec:
  acme:
    email: certs@anthony.bible
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    # example: cross-account zone management for example.com
    # this solver uses ambient credentials (i.e. inferred from the environment or EC2 Metadata Service)
    # to assume a role in a different account
    - selector:
        dnsZones:
          - "anthony.bible"
          - "reg.anthony.bible"
      dns01:
        route53:
          region: us-east-1
          # role: arn:aws:iam::842805395457:role/ExternalRole
